# 1. Create a 3x3x3 array with random values

In [8]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.48491921 0.14352077 0.38402881]
  [0.91009352 0.51177137 0.13874865]
  [0.17820266 0.8855044  0.56108486]]

 [[0.77744593 0.05722506 0.17945497]
  [0.13188903 0.10996863 0.67737272]
  [0.22089435 0.88717538 0.08670769]]

 [[0.76882575 0.87036699 0.10544837]
  [0.66746805 0.01217941 0.32709755]
  [0.43004679 0.28000311 0.65475982]]]


# 2. Create a 5x5 matrix with values 1,2,3,4,5 just below the diagonal

In [72]:
import numpy as np
x = np.diag(1+np.arange(4), k = -1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3. Create a 8x8 matrix and fill it with a checkerboard pattern

In [10]:
import numpy as np
x = np.ones((3,3))
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [12]:
import numpy as np
x= np.random.random((5,5))
print("Original Array:")
print(x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After normalization:")
print(x)

Original Array:
[[0.70713802 0.23200553 0.32857745 0.78617685 0.64366946]
 [0.91138479 0.93695115 0.67376633 0.88475216 0.76515972]
 [0.86264702 0.74651226 0.5248794  0.71674803 0.48246997]
 [0.79442263 0.90237492 0.62993516 0.72026107 0.60494553]
 [0.21007137 0.47801372 0.54867643 0.56134837 0.0935264 ]]
After normalization:
[[0.72752385 0.1641867  0.27868644 0.82123562 0.65227284]
 [0.96968744 1.         0.68795696 0.93811067 0.79631683]
 [0.91190188 0.77420761 0.51143033 0.73891788 0.46114792]
 [0.83101217 0.95900496 0.63598888 0.74308309 0.60636012]
 [0.13818064 0.45586439 0.53964509 0.55466948 0.        ]]


# 5. How to find common values between two arrays? 

In [13]:
import numpy as np
array1 = np.array([1, 2, 3 , 4, 5, 6])
print("Array1: ",array1)
array2 = [10, 9, 8, 7, 6, 5]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [1 2 3 4 5 6]
Array2:  [10, 9, 8, 7, 6, 5]
Common values between two arrays:
[5 6]


# 6.How to get the dates of yesterday, today and tomorrow? 

In [14]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-24
Today:  2020-07-25
Tomorrow:  2020-07-26


# 7. Consider two random array A and B, check if they are equal

In [15]:
import numpy as np
x = np.random.randint(0,2,6)
print("First array:")
print(x)
y = np.random.randint(0,2,6)
print("Second array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

First array:
[0 1 0 0 1 1]
Second array:
[0 1 1 1 0 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0

In [16]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0 : ")
print(x)

Original array:
[0.41459882 0.59643412 0.490305   0.67799534 0.61473707 0.43898795
 0.82450684 0.44071551 0.26466857 0.32376715]
Maximum value replaced by 0 : 
[0.41459882 0.59643412 0.490305   0.67799534 0.61473707 0.43898795
 0.         0.44071551 0.26466857 0.32376715]


# 9. How to print all the values of an array?

In [71]:
import numpy as np
array = np.arange(20)
np. set_printoptions(threshold=np.inf)
print("All values of an array")
print(array)

All values of an array
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


# 10.Subtract the mean of each row of a matrix

In [23]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(3, 6)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.39076444 0.0335518  0.29639378 0.50544635 0.45885739 0.72686093]
 [0.72630598 0.67383982 0.51098335 0.26813073 0.3555679  0.58616944]
 [0.12427349 0.84608888 0.81338482 0.60249986 0.84422626 0.39472746]]

Subtract the mean of each row of the said matrix:

[[-0.01121467 -0.36842732 -0.10558533  0.10346724  0.05687827  0.32488181]
 [ 0.20613978  0.15367362 -0.00918286 -0.25203547 -0.1645983   0.06600323]
 [-0.47992664  0.24188875  0.20918469 -0.00170027  0.24002613 -0.20947267]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?

In [64]:
import numpy as np
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[2. 2. 4. 4. 2. 5. 3. 2. 2. 4.]


# 12.How to get the diagonal of a dot product?

In [75]:
import numpy as np
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.52511339, 0.87555579, 0.87838931, 2.08390358, 1.51538554])

# 13.How to find the most frequent value in an array?

In [38]:
import numpy as np
x = np.random.randint(0, 3, 6)
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[2 1 1 2 1 0]
Most frequent value in the above array:
1


# 14.How to get the n largest values of an array

In [39]:
import numpy as np
x = np.arange(15)
print("Original array:")
print(x)
np.random.shuffle(x)
n = 1
print (x[np.argsort(x)[-n:]])

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[14]


# 15.How to create a record array from a regular array?

In [73]:
import numpy as np
arra1 = np.array([("Teddy", 88.5, 90), ("Adi", 87.5, 99), ("Ritti", 85.5, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T, names='col1, col2, col3', formats = 'S80, f8, i8')
print(result)

Original arrays:
[['Teddy' '88.5' '90']
 ['Adi' '87.5' '99']
 ['Ritti' '85.5' '91']]

Record array;
[(b'Teddy', 88.5, 90) (b'Adi', 87.5, 99) (b'Ritti', 85.5, 91)]
